### ISSUE TITLE
Does not support  308 permanent redirect

### ISSUE THREAD

**Issue by derobert** [libwww-perl/libwww-perl#288]
RFC7538 added status code 308 as an additional redirct. 308 is like 301 except without the POST-to-GET possibility.

I think all that'd be needed to add these to LWP is changing (in UserAgent.pm):

```
 if (   $code == HTTP::Status::RC_MOVED_PERMANENTLY
        or $code == HTTP::Status::RC_FOUND
        or $code == HTTP::Status::RC_SEE_OTHER
        or $code == HTTP::Status::RC_TEMPORARY_REDIRECT)
    {
```
to

```
    if (   $code == HTTP::Status::RC_MOVED_PERMANENTLY
        or $code == HTTP::Status::RC_FOUND
        or $code == HTTP::Status::RC_SEE_OTHER
        or $code == HTTP::Status::RC_TEMPORARY_REDIRECT
        or $code == HTTP::Status::RC_PERMANENT_REDIRECT)
    {

```

Not sure which version of HTTP::Status added that constant.

**Comment by oalders** [comment]
Looks like it was added in HTTP-Message 6.07.

https://metacpan.org/diff/file?target=ETHER/HTTP-Message-6.07/lib%2FHTTP%2FStatus.pm&source=GAAS%2FHTTP-Message-6.06%2Flib%2FHTTP%2FStatus.pm

**Comment by oalders** [comment]
So, we just need to bump the version of `HTTP::Status` directly in the `cpanfile`.  PRs are welcome.  :)

**Comment by oalders** [comment]
This should now be fixed via https://metacpan.org/source/OALDERS/libwww-perl-6.38/dist.ini#L43-46

**Comment by SuneKarlsson** [comment]
But the initial issue does not seem to have been taken care of. That LWP does not follow 308 redirects.

**Comment by galenhuntington** [comment]
This is indeed not fixed, because while `HTTP::Status` was bumped, `UserAgent.pm` was not updated.
